coverage:
  range: 0..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 0
        threshold: null
        base: auto
    patch:
      default:
        target: 0
        threshold: null
        base: auto
